name: Deploy PR previews

on:
    pull_request:
        types: [opened, synchronize, reopened, closed]

permissions:
    contents: write
    pull-requests: write

concurrency:
    group: pr-${{ github.event.pull_request.number }}
    cancel-in-progress: true

env:
    PAGE_DIR: pr-preview-${{ github.event.pull_request.number }}

jobs:
    build-and-commit:
        if: github.event.action != 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Setup Pages
              uses: actions/configure-pages@v5
              with:
                  generator_config_file: next.config.ts

            - name: Restore cache
              uses: actions/cache@v4
              with:
                  path: |
                      .next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-

            - name: Install dependencies
              run: bun install

            - name: Build with Next.js
              run: |
                  export IS_PREVIEW=true
                  export PR_NUMBER=${{ github.event.pull_request.number }}
                  bunx next build

            - name: Move out directory
              run: mv out /tmp/out

            - name: Checkout main
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: Commit changes to main branch
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "action@github.com"
                  mkdir -p ${{ env.PAGE_DIR }}
                  cp -r /tmp/out/* ${{ env.PAGE_DIR }}
                  git add .
                  git commit -m "Deploy PR preview for #${{ github.event.pull_request.number }}"
                  git push origin main

            - name: Comment PR
              uses: actions/github-script@v7
              with:
                  script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `Preview deployed to: https://${context.repo.owner}.github.io/${context.repo.repo}/${process.env.PAGE_DIR}/`
                      })

    cleanup:
        if: github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: Remove preview directory
              run: |
                  rm -rf ${{ env.PAGE_DIR }} || exit 0
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "Remove PR preview for #${{ github.event.pull_request.number }}" && git push origin main || echo "No changes to commit"
